# Setup
title:               Test6666666666666666666666666666
tagline:             'A Test'
description:         'A master's research project, supervised by.'
url:                  https://umproj.github.io/T2
baseurl:             ''
paginate:            4
permalink:           pretty

# About/contact
author:
  name:              MO
  url:               https://twitter.com/
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
