# Setup
title:               
tagline:             
description:         "A master's research project supervised by           Nico Nava.
  Team: F, J, K, M, R
"
url:                  https://umproj.github.io/T2
baseurl:             ''
paginate:            4
permalink:           pretty

# About/contact
author:
  name:              MO
  url:               https://twitter.com/
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
